scraper_image: gcr.io/answers-engine-cloud/tordatascience-scraper-worker-s3cmd
seeder:
  file: ./seeder/seeder.rb
env_vars:
  - name: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
  - name: AWS_S3_BUCKET_NAME
  - name: AWS_S3_TARGET_DIRECTORY
  - name: SCRAPERS_TO_EXPORT