scraper_image: gcr.io/answers-engine-cloud/tordatascience-scraper-worker-s3cmd
seeder:
  file: ./seeder/seeder.rb
input_vars:
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    type: secret
    required: true
  - name: AWS_S3_BUCKET_NAME
    required: true
  - name: AWS_S3_TARGET_DIRECTORY
    required: true
  - name: SCRAPERS_TO_EXPORT
    description: "Enter the scraper names to upload, separated by comma. example: scraper1,scraper2. This will find the exports and upload them ot S3."
    required: true